version: "3.7"

services:
  backend:
    build:
      context: backend
    command: go run server.go
    environment:
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ROOT_PATH="/backend"
    ports:
      - 5001:5001
      - 9229:9229
    # - 9230:9230
    secrets:
      - db_password
    volumes:
      - ./backend:/code:ro
      - ../pfps/:/pfps
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./dbata/:/var/lib/postgresql/data
#     - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5438:5432"
    secrets:
      - db_password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - private

  # frontend:
  #   build:
  #     args:
  #       - NODE_ENV=development
  #     context: frontend
  #     target: development
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - 8080:3000
  #   volumes:
  #     - ./frontend/src:/code/src
  #     - /code/node_modules
  #   networks:
  #     - public
  #   depends_on:
  #     - backend

networks:
  public:
  private:
volumes:
  db-data:
secrets:
   db_password:
     file: db/password.txt
