FROM golang:alpine as base

WORKDIR /app

# System dependencies
RUN apk update \
    && apk add --no-cache \
    build-base \
    ca-certificates \
    git npm \
    && update-ca-certificates

### Development with hot reload and debugger
FROM base AS dev
WORKDIR /app

COPY go.mod /app
COPY .air.toml /app
# Hot reloading mod
RUN go get -u github.com/cosmtrek/air && go install github.com/go-delve/delve/cmd/dlv@latest
EXPOSE 2345 3000
RUN go install github.com/cosmtrek/air@latest


### Executable builder
FROM base AS builder
WORKDIR /app

# Application dependencies
COPY . /app
RUN go mod download \
    && go mod verify

RUN go build -ldflags "-X main.Version=`git tag --sort=-version:refname | head -n 1` -X main.BuildDate=`date -u +\"%Y-%m-%dT%H:%M:%SZ\"` -X main.GitCommit=`git rev-parse --short HEAD` -X main.GitBranch=`git rev-parse --abbrev-ref HEAD` -X main.GitSummary=`git describe --tags --dirty --always` -X main.GitState=`./git-status.sh`" -o maintainer -a .




