version: "3.7"

services:
  todo:
    build:
      context: .
    command: go run main.go
    environment:
      - DATABASE_DB=postgres
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - ROOT_PATH="/"
      - PORT=5001
    ports:
      - 5001:5001
      - 9229:9229
    # - 9230:9230
    secrets:
      - db_password
    volumes:
      - ./app:/app:ro
      - ./routes:/routes:ro
      - ./main.go:/main.go:ro
      - ./go.mod:/go.mod:ro
      - ./go.sum:/go.sum:ro
      - ./static:/static:ro
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./dbata/:/var/lib/postgresql/data
    #     - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5438:5432"
    secrets:
      - db_password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    networks:
      - private

  redis:
    image: redis:latest
    networks:
      - private
    ports:
      - "6379:6379"

networks:
  public:
  private:
volumes:
  db-data:
secrets:
  db_password:
    file: password.txt
